version: "3.3"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
      - static_volume:/static
      - media_volume:/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres

  redis:
    image: redis:7.0.0-alpine
    ports:
    - 6379:6379
    volumes:
      - ./redisdata:/backend/redisdata

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      - backend

  celery:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info -Q base
    volumes:
      - .:/backend/celery
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - backend

volumes:
  postgres_data:
  media_volume:
  static_volume: